# The Basics
- store data in multidimensional arrays
- efficient, fixed types, numpy uses less bytes of memory
- no type checking when iterating through array
- contigous memory (SIMD Vector Processing allowed), Effective Cache Utilization

Using
- MATLAB replacement
- Used as a backend in pandas library
- Machine Learning (tensors)

In [1]:
import numpy as np

In [18]:
a = np.array([1, 2, 3])
print(a)

# 2D array
b = np.array([[1], [2], [3]])
print(b)

# Get dimensions
print("Array b has", b.ndim, "dimensions")

# Get shape rows X cols
print(b.shape)

# Get type
print(a.dtype)

# Specify type
c = np.array([1, 2, 3], dtype='int16')
print(c.dtype)

# Get size
print(c.itemsize)
 
# Get total size
print(c.size * c.itemsize)
print(c.nbytes)



[1 2 3]
[[1]
 [2]
 [3]]
Array b has 2 dimensions
(3, 1)
int64
int16
2
6
6


# Accessing/Changing specific elements rows, columns etc.

In [40]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Get specific element
print(a[0,-1])

# Get specific row
print(a[1, :])

# Get specific column
print(a[:, 2])

# Getting little more fancy [startindex:endindex:stepsize]
print(a[0, 0:5:2])

# change value
a[1, 4] = 11

# Change whole column
a[:, 2] = [-1, -1]
print(a)


# 3D example
b = np.array([[[1, 2],[3, 4]],[[5, 6], [7, 8]]])
print(b[0,0,1])

b[0,0,:] = [-1, -1]

5
[ 6  7  8  9 10]
[3 8]
[1 3 5]
[[ 1  2 -1  4  5]
 [ 6  7 -1  9 11]]
2
