# The Basics
- store data in multidimensional arrays
- efficient, fixed types, numpy uses less bytes of memory
- no type checking when iterating through array
- contigous memory (SIMD Vector Processing allowed), Effective Cache Utilization

Using
- MATLAB replacement
- Used as a backend in pandas library
- Machine Learning (tensors)

In [1]:
import numpy as np

In [18]:
a = np.array([1, 2, 3])
print(a)

# 2D array
b = np.array([[1], [2], [3]])
print(b)

# Get dimensions
print("Array b has", b.ndim, "dimensions")

# Get shape rows X cols
print(b.shape)

# Get type
print(a.dtype)

# Specify type
c = np.array([1, 2, 3], dtype='int16')
print(c.dtype)

# Get size
print(c.itemsize)
 
# Get total size
print(c.size * c.itemsize)
print(c.nbytes)



[1 2 3]
[[1]
 [2]
 [3]]
Array b has 2 dimensions
(3, 1)
int64
int16
2
6
6


# Accessing/Changing specific elements rows, columns etc.

In [40]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Get specific element
print(a[0,-1])

# Get specific row
print(a[1, :])

# Get specific column
print(a[:, 2])

# Getting little more fancy [startindex:endindex:stepsize]
print(a[0, 0:5:2])

# change value
a[1, 4] = 11

# Change whole column
a[:, 2] = [-1, -1]
print(a)


# 3D example
b = np.array([[[1, 2],[3, 4]],[[5, 6], [7, 8]]])
print(b[0,0,1])

b[0,0,:] = [-1, -1]

5
[ 6  7  8  9 10]
[3 8]
[1 3 5]
[[ 1  2 -1  4  5]
 [ 6  7 -1  9 11]]
2


# Initializing Different Types of Arrays

In [79]:
# all 0s matrix
a = np.zeros((5, 5))

# all 1s matrix
b = np.ones((1, 5), dtype='int16')

# any other number
c = np.full((2, 2), 99, dtype='float32')

# any other number full_like
d = np.full_like(c, 4)

# Random decimal numbers [0, 1]
e = np.random.rand(4, 2, 3) # <-- shapes

# Random integer values
f = np.random.randint(0, 2, size=(2, 2)) # start, stop - 1, shape

# Identity matrix
g = np.identity(7)

# repeat array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1.shape)

(1, 9)


In [86]:
# Copying array
a = np.array([1, 2, 3])
b = a.copy()
b[1] = -1

assert a[1] == 2

# Mathematics

In [98]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 3, 2, 1])


# Scalar operations
print(a * 6)
print(a / 6)
print(a + 2) # add 2 to each element
print(a ** 2) # square each element
print(np.sin(a)) # sin of all values


[ 6 12 18 24]
[0.16666667 0.33333333 0.5        0.66666667]
[3 4 5 6]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


## Linear algebra

In [110]:
a = np.full((2, 3), 2)
b = np.full((3, 2), 1)

print(np.matmul(a, b))

# Find determinant
c = np.identity(3)
np.linalg.det(c)

arr = np.ones((3, 3), dtype="int16")
arr[0] = [1, 2, -1]
arr[1] = [2, 2, 1]
arr[2] = [-1, 0, 1]
arr

# Inverse array
np.linalg.inv(arr)

[[6 6]
 [6 6]]


array([[-0.33333333,  0.33333333, -0.66666667],
       [ 0.5       ,  0.        ,  0.5       ],
       [-0.33333333,  0.33333333,  0.33333333]])

# Statistics

In [114]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

print(np.min(stats, axis=1))
print(np.max(stats))

np.sum(stats, axis=1) 
np.sum(stats)

[1 4]
6


21

# Reorganizing arrays

In [122]:
before = np.array([[1, 2, 3], [4, 5, 6]])

after = before.reshape((6, 1))

# vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

new = np.vstack([v1, v2, v1])

# Horizontal stacking
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])



array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [158]:
# Load data from file
url = 'https://raw.githubusercontent.com/KeithGalli/NumPy/master/data.txt'
array = np.genfromtxt(url, delimiter=',')
# convert type of data, make copy
array = array.astype('int32')

# Advanced indexing & Boolean masking
print(array > 50)
print(array[array > 50])

# We can index with a list in NumPy
a = np.array([1, 2, 3, 4, 5])
a[[1,2,4]]

# check if columns has any values > 50
np.any(array > 50, axis=0)

np.all(array != 50, axis=1)

# Multiple conditions
~((array > 50) & (array < 100))



[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[196  75 766  75  55 999  78  76  88]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
